CAMERA_INDEX = 0

FRAME_WIDTH = 640
FRAME_HEIGHT = 480
TARGET_FPS = 20

YOLO_MODEL = "yolo11n.pt"
CONFIDENCE_THRESHOLD = 0.50

ACTIVITY_WINDOW = 15
ACTIVITY_MIN_FRAMES = 5

DUPLICATE_COOLDOWN = 2.0

RECORDINGS_DIR = "recordings"
LOGS_DIR = "logs"

JPEG_QUALITY = 80